# Version de l'API et informations générales
openapi: 3.0.0
info:
  version: 1.0.0
  title: Argent Bank API
  description: API documentation for transaction management in Argent Bank.

# Serveurs où l'API est hébergée
servers:
  - url: http://localhost:3001/api/v1

# Définition des routes et des endpoints
paths:
  # Endpoint pour obtenir toutes les transactions
  /transactions:
    get:
      summary: Get all transactions
      description: Retrieve a list of all transactions for the authenticated user.
      responses:
        '200':
          description: A list of transactions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '401':
          description: Unauthorized access.

  # Endpoint pour des opérations spécifiques à une transaction par ID
  /transactions/{transactionId}:
    get:
      summary: Get transaction by ID
      description: Retrieve details of a specific transaction by its ID.
      parameters:
        - name: transactionId
          in: path
          required: true
          description: ID of the transaction to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: Details of the transaction.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '404':
          description: Transaction not found.

    put:
      summary: Update a transaction
      description: Update details of a specific transaction by its ID.
      parameters:
        - name: transactionId
          in: path
          required: true
          description: ID of the transaction to update.
          schema:
            type: string
      requestBody:
        description: Transaction data to update.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionUpdate'
      responses:
        '200':
          description: Transaction updated successfully.
        '404':
          description: Transaction not found.

    delete:
      summary: Delete a transaction
      description: Delete a specific transaction by its ID.
      parameters:
        - name: transactionId
          in: path
          required: true
          description: ID of the transaction to delete.
          schema:
            type: string
      responses:
        '204':
          description: Transaction deleted successfully.
        '404':
          description: Transaction not found.

# Définition des schémas utilisés dans les réponses et les requêtes
components:
  schemas:
    # Schéma pour une transaction
    Transaction:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the transaction.
        date:
          type: string
          format: date
          description: Date of the transaction.
        description:
          type: string
          description: Description of the transaction.
        amount:
          type: number
          description: Amount of the transaction.
        balance:
          type: number
          description: Balance after the transaction.
        type:
          type: string
          description: Type of the transaction.
        category:
          type: string
          description: Category of the transaction.
        notes:
          type: string
          description: Additional notes for the transaction.

    # Schéma pour la mise à jour d'une transaction
    TransactionUpdate:
      type: object
      properties:
        category:
          type: string
          description: Updated category of the transaction.
        notes:
          type: string
          description: Updated notes for the transaction.